# docker-compose.yaml
version: '3.3'
services:
  jenkins:
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    build:
      context: .
      dockerfile: jenkins/Dockerfile