---
- name: Install Whanos project
  hosts: whanos
  remote_user: root
  connection: ssh
  become: yes
  become_user: root
  gather_facts: yes
  tasks:
  - name: Install packages that allow apt to be used over HTTPS
    ansible.builtin.apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

  - name: Add an apt signing key for Docker
    ansible.builtin.apt_key:
      url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
      state: present

  - name: Add apt repository for stable version
    ansible.builtin.apt_repository:
      repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
      state: present
      filename: docker

  - name: Install Docker and its dependecies
    ansible.builtin.apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker
      - docker.io
      - docker-compose
      - docker-registry
    notify:
      - docker restart
    
  - name: Install Make
    ansible.builtin.apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - make

  - name: Remove swapfile from /etc/fstab
    ansible.builtin.mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    ansible.builtin.command: swapoff -a
    when: ansible_swaptotal_mb > 0

  # - name: Add an apt signing key for Kubernetes
  #   ansible.builtin.apt_key:
  #     url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
  #     state: present

  - name: Adding apt repository for Kubernetes
    ansible.builtin.apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list

  - name: Install Kubernetes binaries
    ansible.builtin.apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - kubelet 
        - kubeadm 
        - kubectl

  - name: Download Minikube
    ansible.builtin.get_url:
      url: https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
      dest: /tmp

  - name: Install Minikube
    apt: deb="/tmp/minikube_latest_amd64.deb"

  - name: Copy Jenkins Docker compose
    ansible.builtin.copy:
      src: ../docker-compose.yaml
      dest: /tmp

  - name: Copy Images folder
    ansible.builtin.copy:
      src: ../images
      dest: /tmp

  - name: Copy Jenkins configuration
    ansible.builtin.copy:
      src: ../jenkins
      dest: /tmp

  - name: Copy .env file
    ansible.builtin.copy:
      src: ../.env
      dest: /tmp
  
  - name: Copy Makefile
    ansible.builtin.copy:
      src: ../Makefile
      dest: /tmp

  - name: Run Docker daemon
    ansible.builtin.command:
      cmd: make run
      chdir: /tmp